version: "3.7"
services:
  cockroachdb:
    container_name: ${REPOSITORY_NAME}-cockroachdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure --advertise-addr ${DATABASE_HOST}
    ports:
      - "${DATABASE_PORT}:26257"
      - "8081:8080"
    volumes:
      - "${PWD}/.cache/cockroach:/cockroach/cockroach-data"
    environment:
      - COCKROACH_USER=${DATABASE_USER}
      - COCKROACH_PASSWORD=${DATABASE_PASSWORD}
      - COCKROACH_DATABASE=${DATABASE_NAME}
    mem_limit: 1024m
    mem_reservation: 512M
    cpus: 0.5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024m
        reservations:
          cpus: "0.25"
          memory: 512M

  ipfs:
    container_name: ${REPOSITORY_NAME}-ipfs
    image: ipfs/kubo:latest
    hostname: ipfs
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
    volumes:
      - "${PWD}/.cache/ipfs:/data/ipfs"
      - "${PWD}/.cache/ipfs-export:/export"
    environment:
      - IPFS_PROFILE=server
    mem_limit: 1024m
    mem_reservation: 512M
    cpus: 0.5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024m
        reservations:
          cpus: "0.25"
          memory: 512M

  redis:
    container_name: ${REPOSITORY_NAME}-redis
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ${PWD}/.cache/redis:/data

  minio:
    container_name: ${REPOSITORY_NAME}-minio
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "${S3_PORT}:9000"
      - "9001:9001"
    expose:
      - "9000"
      - "9001"
    volumes:
      - ${PWD}/.cache/minio:/data
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
      MINIO_REGION: ${S3_REGION}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://${S3_ENDPOINT}:${S3_PORT}/minio/health/live",
        ]
      interval: 30s
      timeout: 20s
      retries: 3
