components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas:
        RegisterUserDTO:
            properties:
                firstName:
                    type: string
                    description: 'The user''s first name'
                    example: John
                    maxLength: 50
                    minLength: 1
                    pattern: '^[a-zA-Z0-9_]*$'
                lastName:
                    type: string
                    description: 'The user''s last name'
                    example: Doe
                    maxLength: 50
                    minLength: 1
                    pattern: '^[a-zA-Z0-9_]*$'
                email:
                    type: string
                    description: 'The user''s email'
                    example: john.doe@example.com
                    pattern: '(?:[a-z0-9!#$%&''*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&''*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])'
                password:
                    description: 'The user''s password'
                    example: superDuperStrongPassword
                    maxLength: 64
                    minLength: 6
                username:
                    type: string
                    description: 'The user''s useranme.'
                    example: johndoe
                    maxLength: 32
                    minLength: 1
                dateOfBirth:
                    type: string
                    format: date
                    description: 'The user''s date of birth'
                    example: '2000-10-12'
                height:
                    type: integer
                    format: int32
                    description: 'The user''s height in centimeters'
                    example: 182
                    minimum: 0
                    maximum: 300
                weight:
                    type: integer
                    format: int32
                    description: 'The user''s weight in kilograms'
                    example: 65
                    minimum: 0
                    maximum: 300
            required:
                - password
                - username
            type: object
            additionalProperties: false
    securitySchemes: {}
info:
    title: Neuronek
    version: 1.0.0
    description: 'Early version of Neuronek API.'
    contact:
        name: 'Jakub Olan'
        email: keinsell@protonmail.com
openapi: 3.0.0
paths:
    /user/register:
        post:
            operationId: register-user
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema: {}
                            examples:
                                'Example 1':
                                    value: {id: 1, email: "", name: 'John Doe', phoneNumbers: []}
                '201':
                    description: 'Created user successfully'
                    content:
                        application/json:
                            schema:
                                type: string
                            examples:
                                'Example 1':
                                    value: cl864jzha0005ted5rfkcrik3
            description: 'Create a new user in Neuronek system.'
            tags:
                - User
            security: []
            parameters: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterUserDTO'
servers:
    -
        url: /api
tags:
    -
        name: User
        description: 'Operations about users'
        externalDocs:
            description: 'Find out more about users'
            url: 'http://swagger.io'
